services:
  api:
    build:
      context: ./tickets-api
    ports:
      - "8080:80"
    volumes:
      - ./tickets-api:/var/www/html
      - /var/www/html/vendor
    restart: unless-stopped
    depends_on:
      - db
  client:
    build:
      context: ./tickets-client
    ports:
      - "5173:5173"
    volumes:
      - ./tickets-client:/app
      - /app/node_modules
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: